### PR TITLE
Bicatofactionsinbicat

### PR DESCRIPTION
**Pull request by Kfwullaert**

### CODE REVIEW

**Comment by rmatthes** [comment]
@Kfwullaert Do you really want me to pull your new file with the reordering? It does not seem needed in the other one. I see that the joker is gone since there is only one identified statement. So, your question is already visible in the code (without executing it).

**Comment by Kfwullaert** [comment]
> @Kfwullaert Do you really want me to pull your new file with the reordering? It does not seem needed in the other one. I see that the joker is gone since there is only one identified statement. So, your question is already visible in the code (without executing it).

No that's not necessary. The problem is indeed just identified with admitted and the statement should be pretty clear stated.

**Comment by Kfwullaert** [comment]
> > @Kfwullaert Do you really want me to pull your new file with the reordering? It does not seem needed in the other one. I see that the joker is gone since there is only one identified statement. So, your question is already visible in the code (without executing it).
> 
> No that's not necessary. The problem is indeed just identified with admitted and the statement should be pretty clear stated.

**Comment by Kfwullaert** [comment]
@rmatthes the reordering should not be in there, so don't pull it indeed! I'll remove the file at the next commit.

**Pull request merged**
