### PR TITLE
Continuity signature functor

### PR DESCRIPTION
**Pull request by Kfwullaert**
This is NOT yet ready to be MERGED.
Open gaps are explained in https://github.com/benediktahrens/monoidal/issues/229
This PR is created so that you can already have a look at it.

### CODE REVIEW

**Comment by rmatthes** [comment]
@Kfwullaert I already see that you develop this in completely new files, so there is no risk of conflicts even when I now modify the files in package SubstitutionSystems and your PR hangs around for some time.

**Comment by Kfwullaert** [comment]
@rmatthes Yes indeed, that was one of the purposes. 
 also did it because I think, at the end, it would be good to have the file MultiSorted_alt.v divided.
Currently, there is both the definition of the signature functor and the omega-cocontinuity. I think it would be better to have the definition and the one I have written down in a single file (and a natural isomorphism between the two, what I am currently doing inside, something called MultiSortedSignatureFunctor.v and two files, one MultiSortedContinuity and MultiSortedCocontinuity. I think separating it how I've currently done also helps with that.

**Comment by rmatthes** [comment]
This would certainly mean to take out the strength definitions as well. My concern is that there are many parameters that have to be given as arguments again and again.

**Comment by rmatthes** [comment]
@Kfwullaert I now tend to division as well, see my latest commit to my working branch. I would not bundle all these prerequisites. I now use a mixture of local redefinitions (that require unfolding) and lets.
Please modify your PR so that it can again be merged (maybe this is about the file list of the package) and ensure it compiles. Then, I would prefer to merge it and play around with it instead of writing comments on your code.

**Comment by Kfwullaert** [comment]
@rmatthes I'll do this tomorrow. I was not planning on leaving the prerequisites in that file. But I always do this first in order to avoid having merging issues if other people would change the files where those lemmas should be placed. So before making a "real PR" or saying that it is ready to be merged in my opinion, I would've moved it.

**Comment by rmatthes** [comment]
Okay, I can refrain from changing files other than the ones I added today or yesterday until you tell me.

**Comment by rmatthes** [comment]
I just made another commit that also added a bit of material for the lineator constructions (that should not be of concern for this PR). @Kfwullaert Please inform me when I should stop doing changes to files you might import or touch in your PR.

**Comment by Kfwullaert** [comment]
@rmatthes I did not meant that you shouldn't change files that I would use. I assumed that you were talking previously that I should remove the file "general_lemmas.v" and move the content of that file in the appropriate files.

**Comment by rmatthes** [comment]
As announced, I merge before studying it properly.

**Pull request merged**
