### PR TITLE
Terminal to ghss

### PR DESCRIPTION
**Pull request by Kfwullaert**

### CODE REVIEW

**Comment by rmatthes** [comment]
I think that the code is placed badly. Could you please move it into a new file, maybe under the name ConstructionOfGHSS.v?

**Comment by Kfwullaert** [comment]
> I think that the code is placed badly. Could you please move it into a new file, maybe under the name ConstructionOfGHSS.v?

I have moved it.

**Comment by rmatthes** [comment]
@Kfwullaert I am sorry to bother you again, but you should remove the 10 extra import statements from SigmaMonoids.v

**Comment by rmatthes** [comment]
I did that last correction immediately afterwards.

**Pull request merged**
