### PR TITLE
Continuity signature functor

### PR DESCRIPTION
**Pull request by Kfwullaert**

### CODE REVIEW

**Comment by rmatthes** [comment]
@Kfwullaert Can you please give me an idea of the status of this PR? It seems you inherit the TODO joker from other files. This should never be allowed. Please make the Lemma local. Do you expect more conditions on C to be necessary?

**Comment by Kfwullaert** [comment]
@rmatthes Sorry for the late reply, I will change the TODO_JOKER to be local and make a separate one in the other file.
Reagarding the conditions, all conditions that are needed are listed in is_omega_cont_MultiSortedSigToFunctor (these should be sufficient conditions).
This PR was for you to see these conditions and I've started giving the proof of omega-continuity of Id_H, even though this should be straightforward, it is just messing a little bit between the concrete limits and the construction of the concrete limits using the general notion of a limit w.r.t. a diagram.

**Comment by rmatthes** [comment]
@Kfwullaert I just wondered if forming the pointwise coproduct with a constant functor is not easier than the general case. Id_H is such a situation. However, I am aware that the first summand is constantly Id, while Id itself is no constant  functor.

**Comment by rmatthes** [comment]
Currently, there is one use of a joker in `I_coproduct_distribute_over_omega_limit_HSET_inverse` and one Admitted in the file where all is put together.

**Comment by rmatthes** [comment]
I again merge without studying the code in detail.

**Comment by rmatthes** [comment]
Even if the PR is merged, I use this space to tell you (@Kfwullaert ) that I just committed something to the working branch that should make it easy to fill the last gap in `MultiSortedSignatureFunctorEquivalence.v`. To finish it, you only need very general lemmas about binary products: binproduct of a functor with the constantly terminal object does nothing, and binproduct of functors is commutative. If they are not in the library, then please put them there. By no means treat it for this awkward nested functor category specifically.

**Comment by rmatthes** [comment]
However, that the order of the product formation is not respected does rather look like a (small) problem with your definition.

**Comment by rmatthes** [comment]
I identified the problem. The definition `hat_exp_functor_list'` should be replaced by `hat_exp_functor_list''` that I just committed.

**Pull request merged**
