### PR TITLE
Monoidal coherence instances

### PR DESCRIPTION
**Pull request by nmvdw**
I proved all admits that were an instance of the monoidal coherence theorem

### CODE REVIEW

**Comment by rmatthes** [comment]
Maybe not so prominent. I can do that.

**Comment by nmvdw** [comment]
I also fixed the remaining admitted, so now the file is free of admits.

**Comment by rmatthes** [comment]
So, you confirm that the last remaining lemma is really just the opposite direction of the previous one.

**Comment by nmvdw** [comment]
Indeed, it was just a matter of turning that equation around.

**Pull request merged**
